### ISSUE TITLE
Suggested optional config files for editors?

### ISSUE THREAD

**Issue by rmsthebest** [esp-rs/esp-generate#42]
It could be nice to let the user select their editor during configuration and get a file similar to the .vscode config, but for other editors such as neovim or helix

This is what helix would look like for example.
`.helix/languages.toml`
```toml
[[language]]
name = "rust"

[language-server.rust-analyzer.config]
check.allTargets = false
cargo.target = "riscv32imac-unknown-none-elf"
```
