### ISSUE TITLE
Consider setting the MSRV toolchain in rust-toolchain.toml

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-generate#86]
We could one step further in the rust-toolchain.toml by doing something like this:

```toml
[toolchain]
channel    = "stable-1.84"
components = ["rust-src"]
targets = ["riscv32imc-unknown-none-elf"]
```

Unfortunately I think this will only work on RISC-V until Xtensa is upstreamed.
